## This configuration was generated by terraform-provider-oci


data "oci_core_subnet" "publicsubnets" { 
  compartment_id = var.compartment_id 
  # only retain the subnets that allow public traffic 
  filter { 
     name = "prohibit_public_ip_on_vnic" values = [ "false"] 
  }
}


output "publicsubnet" { 
  value = data.oci_core_subnet.publicsubnets[0] 
}

resource oci_apigateway_gateway export_gb-tour-2020-gateway {
  #certificate_id = <<Optional value not found in discovery>>
  compartment_id = var.compartment_ocid
  display_name  = "cloudnative-2021-gateway"
  endpoint_type = "PUBLIC"
  freeform_tags = {
  }
  network_security_group_ids = [
  ]
  response_cache_details {
    #authentication_secret_id = <<Optional value not found in discovery>>
    #authentication_secret_version_number = <<Optional value not found in discovery>>
    #connect_timeout_in_ms = <<Optional value not found in discovery>>
    #is_ssl_enabled = <<Optional value not found in discovery>>
    #is_ssl_verify_disabled = <<Optional value not found in discovery>>
    #read_timeout_in_ms = <<Optional value not found in discovery>>
    #send_timeout_in_ms = <<Optional value not found in discovery>>
    #servers = <<Optional value not found in discovery>>
    type = "NONE"
  }
  subnet_id = data.oci_core_subnet.publicsubnets[0].id
}
